FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY ./ /app/
COPY package*.json /app/
WORKDIR /app
ARG VITE_API_URL=${VITE_API_URL}
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN npx -y playwright install --with-deps
