"""permissions

Revision ID: 060f2d7bce66
Revises: 262066904794
Create Date: 2024-12-21 08:57:00.191939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060f2d7bce66'
down_revision: Union[str, None] = '262066904794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.add_column('actor', sa.Column('group_owner_id', sa.Uuid(), nullable=True))
    op.add_column('actor', sa.Column('group_read', sa.Boolean(), nullable=False))
    op.add_column('actor', sa.Column('group_write', sa.Boolean(), nullable=False))
    op.add_column('actor', sa.Column('member_read', sa.Boolean(), nullable=False))
    op.add_column('actor', sa.Column('member_write', sa.Boolean(), nullable=False))
    op.add_column('actor', sa.Column('other_read', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'actor', 'org', ['group_owner_id'], ['id'])
    op.create_foreign_key(None, 'actor', 'user', ['owner_id'], ['id'])
    op.drop_constraint('org_owner_id_fkey', 'org', type_='foreignkey')
    op.drop_constraint('org_group_owner_id_fkey', 'org', type_='foreignkey')
    op.drop_column('org', 'member_read')
    op.drop_column('org', 'group_write')
    op.drop_column('org', 'other_read')
    op.drop_column('org', 'group_owner_id')
    op.drop_column('org', 'owner_id')
    op.drop_column('org', 'member_write')
    op.drop_column('org', 'group_read')
    op.drop_constraint('person_group_owner_id_fkey', 'person', type_='foreignkey')
    op.drop_constraint('person_owner_id_fkey', 'person', type_='foreignkey')
    op.drop_column('person', 'member_read')
    op.drop_column('person', 'group_write')
    op.drop_column('person', 'other_read')
    op.drop_column('person', 'group_owner_id')
    op.drop_column('person', 'owner_id')
    op.drop_column('person', 'member_write')
    op.drop_column('person', 'group_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('group_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('person', sa.Column('member_write', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('person', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('group_owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('other_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('person', sa.Column('group_write', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('person', sa.Column('member_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('person_owner_id_fkey', 'person', 'user', ['owner_id'], ['id'])
    op.create_foreign_key('person_group_owner_id_fkey', 'person', 'org', ['group_owner_id'], ['id'])
    op.add_column('org', sa.Column('group_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('org', sa.Column('member_write', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('org', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('org', sa.Column('group_owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('org', sa.Column('other_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('org', sa.Column('group_write', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('org', sa.Column('member_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('org_group_owner_id_fkey', 'org', 'org', ['group_owner_id'], ['id'])
    op.create_foreign_key('org_owner_id_fkey', 'org', 'user', ['owner_id'], ['id'])
    op.drop_constraint(None, 'actor', type_='foreignkey')
    op.drop_constraint(None, 'actor', type_='foreignkey')
    op.drop_column('actor', 'other_read')
    op.drop_column('actor', 'member_write')
    op.drop_column('actor', 'member_read')
    op.drop_column('actor', 'group_write')
    op.drop_column('actor', 'group_read')
    op.drop_column('actor', 'group_owner_id')
    op.drop_column('actor', 'owner_id')
    # ### end Alembic commands ###
