"""init

Revision ID: 26546f9d4a4b
Revises: 74da866674fd
Create Date: 2024-11-19 16:26:47.667975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26546f9d4a4b'
down_revision: Union[str, None] = '74da866674fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organisation_id_fkey', 'organisation', type_='foreignkey')
    op.create_foreign_key(None, 'organisation', 'actor', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisation', type_='foreignkey')
    op.create_foreign_key('organisation_id_fkey', 'organisation', 'actor', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
