"""person has just a name

Revision ID: 27f32bb94723
Revises: 9e612c4af16b
Create Date: 2024-11-29 08:56:16.235065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f32bb94723'
down_revision: Union[str, None] = '9e612c4af16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('person', 'lastname')
    op.drop_column('person', 'firstname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('person', 'name')
    # ### end Alembic commands ###
