"""init

Revision ID: 55a86a21227d
Revises: 2dba1d25ecbc
Create Date: 2024-11-26 06:37:54.634105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a86a21227d'
down_revision: Union[str, None] = '2dba1d25ecbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('person_user_id_fkey', 'person', type_='foreignkey')
    op.drop_column('person', 'user_id')
    op.add_column('user', sa.Column('person_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'person_id')
    op.add_column('person', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('person_user_id_fkey', 'person', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
