"""col-permissions

Revision ID: 691fbbe24d41
Revises: a4302dc4176b
Create Date: 2025-01-24 12:56:12.174721

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.core.db.models import PermissionsType

# revision identifiers, used by Alembic.
revision: str = "691fbbe24d41"
down_revision: Union[str, None] = "a4302dc4176b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    contact_default_permissions = {
        "phone_number": {
            "group_read": True,
            "member_read": True,
            "other_read": False,
        },
        "email_address": {
            "group_read": True,
            "member_read": True,
            "other_read": False,
        },
    }
    # ### commands auto generated by Alembic - please adjust! ###
    import json
    op.add_column(
        "contact",
        sa.Column(
            "permissions",
            PermissionsType(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text(f"'{json.dumps(contact_default_permissions)}'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contact", "permissions")
    # ### end Alembic commands ###
