"""init

Revision ID: 711d67ade90e
Revises: b7700a1f11e0
Create Date: 2024-11-20 14:19:06.417355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711d67ade90e'
down_revision: Union[str, None] = 'b7700a1f11e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisationmembers', sa.Column('membership_data', sa.String(), nullable=False))
    op.drop_column('organisationmembers', 'schema_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisationmembers', sa.Column('schema_data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('organisationmembers', 'membership_data')
    # ### end Alembic commands ###
