"""init

Revision ID: 90c1e6e38364
Revises: 26546f9d4a4b
Create Date: 2024-11-19 16:30:04.586922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c1e6e38364'
down_revision: Union[str, None] = '26546f9d4a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organisation_id_fkey', 'organisation', type_='foreignkey')
    op.create_foreign_key(None, 'organisation', 'actor', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisation', type_='foreignkey')
    op.create_foreign_key('organisation_id_fkey', 'organisation', 'actor', ['id'], ['id'])
    # ### end Alembic commands ###
