"""init

Revision ID: b7700a1f11e0
Revises: e4ec4d27abb0
Create Date: 2024-11-20 10:21:07.567562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7700a1f11e0'
down_revision: Union[str, None] = 'e4ec4d27abb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('child')
    op.drop_table('parent')
    op.add_column('organisationmembers', sa.Column('schema_data', sa.String(), nullable=False))
    op.drop_column('organisationmembers', 'extra_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisationmembers', sa.Column('extra_data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('organisationmembers', 'schema_data')
    op.create_table('parent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='parent_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('child',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['parent.id'], name='child_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='child_pkey')
    )
    op.drop_table('person')
    # ### end Alembic commands ###
