"""init

Revision ID: e4ec4d27abb0
Revises: 90c1e6e38364
Create Date: 2024-11-20 01:24:08.725950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ec4d27abb0'
down_revision: Union[str, None] = '90c1e6e38364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('organisation_id_fkey', 'organisation', type_='foreignkey')
    op.create_foreign_key(None, 'organisation', 'actor', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisation', type_='foreignkey')
    op.create_foreign_key('organisation_id_fkey', 'organisation', 'actor', ['id'], ['id'], ondelete='CASCADE')
    op.drop_table('child')
    op.drop_table('parent')
    # ### end Alembic commands ###
