name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Do not deploy in the main repository, only in user projects
    if: github.repository_owner != 'fastapi'
    runs-on:
      - self-hosted
      - staging
    # Allow to load variables and secrets from github environments
    environment: staging
    env:
      ENVIRONMENT: staging
      DOMAIN: ${{ vars.DOMAIN }}
      STACK_NAME: ${{ vars.STACK_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ vars.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ vars.SMTP_HOST }}
      SMTP_USER: ${{ vars.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAILS_FROM_EMAIL: ${{ vars.EMAILS_FROM_EMAIL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      BACKEND_CORS_ORIGINS: ${{vars.BACKEND_CORS_ORIGINS}}
      PROJECT_NAME: ${{vars.PROJECT_NAME}}
      FRONTEND_HOST: ${{vars.FRONTEND_HOST}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml --project-name ${{ vars.STACK_NAME }} build
      - run: docker compose -f docker-compose.yml --project-name ${{ vars.STACK_NAME }} up -d
